version: '3.7'

services:
  web-CHANGEME:
    container_name: web-CHANGEME
    build: .
    restart: always
    volumes:
      - /storage/CHANGEME:/app
    ports:
      - 5001:5001
    networks:
      - lan-network

networks:
   lan-network:
      external:
         name: docker-lan