version: '3.7'

services:
  keycloak:
    container_name: keycloak-app
    build: .
    restart: always
    environment:
      KEYCLOAK_ADMIN_USER: ${KEYCLOAK_ADMIN_USERNAME}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KEYCLOAK_DATABASE_HOST: ${POSTGRESQL_HOST}
      KEYCLOAK_DATABASE_PORT: ${POSTGRESQL_PORT}
      KEYCLOAK_DATABASE_NAME: ${POSTGRESQL_DATABASE_NAME}
      KEYCLOAK_DATABASE_USER: ${POSTGRESQL_DATABASE_USERNAME}
      KEYCLOAK_DATABASE_PASSWORD: ${POSTGRESQL_DATABASE_PASSWORD}
      KEYCLOAK_PRODUCTION: "true"
      KEYCLOAK_ENABLE_HTTPS: "false"
    ports:
      - "8080:8080"
    networks:
      - lan-network

networks:
   lan-network:
      external:
         name: docker-lan