version: '3.7'

services:
  keycloak:
    container_name: keycloak-app
    build: .
    restart: always
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=YourStr0ngPassw0rd
      - KC_CACHE=local
      - KC_HTTP_ENABLED=true
      - KC_HOSTNAME_STRICT=false
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres-docker-hostname:5432/keycloak
      - KC_DB_USERNAME=postgres
      - KC_DB_PASSWORD=postgres
    ports:
      - "8080:8080"
    networks:
      - lan-network

networks:
   lan-network:
      external:
         name: docker-lan
