version: '3.7'

services:
  postgres:
    image: postgres:13.2
    container_name: keycloak-db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRESQL_DB}
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASS}
    volumes:
     - /storage/CHANGEME:/var/lib/postgresql/data
    networks:
      - lan-network
    ports:
     - 5432:5432

  keycloak:
    depends_on:
      - postgres
    container_name: keycloak-app
    environment:
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_DATABASE: ${POSTGRESQL_DB}
      DB_USER: ${POSTGRESQL_USER}
      DB_PASSWORD: ${POSTGRESQL_PASS}
    image: jboss/keycloak:${KEYCLOAK_VERSION}
    ports:
      - "8080:8080"
    restart: always
    networks:
      - lan-network

networks:
   lan-network:
      external:
         name: docker-lan