version: '3.7'

services:
  elasticsearch:
    container_name: elastic
    build:
      context: .
      dockerfile: Elastic/Dockerfile
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - /storage/CHANGEME/data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      # - xpack.monitoring.enabled=true
      # - xpack.watcher.enabled=false
      # - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
      - lan-network

  kibana:
    container_name: kibana
    build:
      context: .
      dockerfile: Kibana/Dockerfile
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - lan-network

networks:
   lan-network:
      external:
         name: docker-lan