version: '3.7'

services:
  hashi-vault:
    container_name: hashi-vault
    build: .
    restart: "always"
    volumes:
      - /docker/storage/storage-vault/files:/vault/file/:rw
      - /docker/storage/storage-vault/logs:/vault/logs/:rw
      - /docker/storage/storage-vault/data:/vault/data/:rw
      - /docker/storage/storage-vault/config:/vault/config/:rw
    ports:
      - 8200:8200
    cap_add:
      - IPC_LOCK
    entrypoint: vault server -config /vault/config/config.hcl

networks:
   lan-network:
     external:
       name: docker-lan