version: '3.7'

services:
  web-CHANGEME:
    container_name: web-CHANGEME
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT="production"
      - ASPNETCORE_URLS=http://*:5001
    ports:
      - 5001:5001
    networks:
      - lan-network

networks:
   lan-network:
      external:
         name: docker-lan