version: '3.7'

services:
  redis:
    container_name: redis
    build: .
    restart: "always"
    ports:
      - 6379:6379
    volumes:
      - /storage/redis/data:/data
    networks:
      - lan-network

networks:
   lan-network:
      external:
         name: docker-lan